# Generated by Django 5.2.2 on 2025-07-19 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Unknown Author', max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalMaster',
            fields=[
                ('hospital', models.CharField(max_length=10)),
                ('speciality', models.CharField(max_length=100)),
                ('spltycode', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('subcatg', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('published_date', models.DateField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.author')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalVisit',
            fields=[
                ('rslno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('thevalue', models.IntegerField()),
                ('thecode', models.CharField(max_length=20)),
                ('speciality', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=1)),
                ('themnth', models.IntegerField()),
                ('theyr', models.IntegerField()),
                ('hospital', models.CharField(max_length=10)),
                ('theday', models.IntegerField()),
                ('spltycode', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('subcatg', models.CharField(max_length=50)),
                ('hospital_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='app.hospitalmaster')),
            ],
        ),
    ]
