# Generated by Django 5.2.6 on 2025-09-09 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_surgeries_remove_book_author_delete_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='surgeries',
            new_name='surgery',
        ),
    ]
